#!/usr/bin/env python3
"""Rebuild generated files for the Lumenis Corporate Design System.

  python3 build.py

1. components/core/Icon.jsx  <- assets/icons/*.svg   (inline path data, no runtime fetch)
2. _ds_bundle.js             <- components/**/*.jsx  (plain-JS namespace for preview cards)

Components are written with React.createElement (no JSX syntax) so the bundle is a
straight concatenation: `export ` is stripped and everything is exposed on one global.
"""
import pathlib, re, json

ROOT = pathlib.Path(__file__).resolve().parent
NAMESPACE = "LumenisCorporateDesignSystem"
ICON_ORDER = ["crossover", "burst", "zigzag", "wave", "sparkle", "rings", "star", "cross", "lines", "orbit"]

def build_icons():
    icons = {}
    for name in ICON_ORDER:
        svg = (ROOT / "assets/icons" / f"{name}.svg").read_text()
        view = re.search(r'viewBox="([^"]+)"', svg).group(1)
        paths = re.findall(r'<path d="([^"]+)"', svg)
        icons[name] = {"viewBox": view, "paths": paths}
    src = (
        "const ICONS=" + json.dumps(icons, separators=(",", ":")) + ";\n"
        "export const ICON_NAMES=" + json.dumps(ICON_ORDER) + ";\n\n"
        "export function Icon({name='burst',size='24px',scale='small',color='currentColor',title}){\n"
        "const ic=ICONS[name]||ICONS.burst;\n"
        "const sw=scale==='large'?2:1;\n"
        "return React.createElement('svg',{viewBox:ic.viewBox,width:size,height:size,fill:'none',stroke:color,strokeWidth:sw,"
        "role:title?'img':undefined,'aria-label':title||undefined,'aria-hidden':title?undefined:'true',style:{display:'inline-block',flexShrink:0,overflow:'visible'}},\n"
        "ic.paths.map((d,i)=>React.createElement('path',{key:i,d,vectorEffect:'non-scaling-stroke'})));\n"
        "}\n"
    )
    (ROOT / "components/core/Icon.jsx").write_text(src)

def build_bundle():
    files = sorted((ROOT / "components").rglob("*.jsx"))
    # Logo must come before components that reference it (NavBar, SplitLayout, SocialPost).
    files.sort(key=lambda p: (0 if p.name == "Logo.jsx" else 1, str(p)))
    exported, chunks = [], []
    for f in files:
        code = f.read_text()
        exported += re.findall(r"export (?:function|const) (\w+)", code)
        chunks.append(f"/* {f.relative_to(ROOT)} */\n" + re.sub(r"^export ", "", code, flags=re.M))
    out = (
        f"/* Generated by build.py — do not edit. Components: {', '.join(exported)} */\n"
        "(function(){\n" + "\n".join(chunks) +
        f"\nwindow.{NAMESPACE}={{{','.join(exported)}}};\n}})();\n"
    )
    # Escape non-ASCII so the bundle decodes correctly even when served without a charset.
    out = out.encode("ascii", "backslashreplace").decode("ascii").replace("\\x", "\\u00")
    (ROOT / "_ds_bundle.js").write_text(out)
    return exported

if __name__ == "__main__":
    build_icons()
    names = build_bundle()
    print(f"window.{NAMESPACE}: {', '.join(names)}")
